import { strict as assert } from 'assert'
import * as fs from 'fs'
import * as path from 'path'
import { FEATURE_CATALOG } from '../../src/features/feature-catalog'

const ROOT = path.resolve(__dirname, '../..')

/** Parses FEATURES.md into (category, featureName) pairs from its tables. */
function parseCheatSheet(): Array<{ category: string; name: string }> {
  const text = fs.readFileSync(path.join(ROOT, 'FEATURES.md'), 'utf8')
  const out: Array<{ category: string; name: string }> = []
  let category = ''
  for (const line of text.split(/\r?\n/)) {
    const heading = /^## (.+)$/.exec(line)
    if (heading) {
      category = heading[1].trim()
      continue
    }
    const row = /^\| (.+?) \|/.exec(line)
    if (!row || category === 'Where to find things') {
      continue
    }
    const first = row[1].trim()
    if (first === 'Feature' || /^-+$/.test(first.replaceAll('-', '-'))) {
      continue
    }
    if (/^[-: ]+$/.test(first)) {
      continue
    }
    // Strip the sub-entry arrow and inline code formatting
    const name = first.replace(/^↳\s*/, '').replaceAll('`', '').trim()
    out.push({ category, name })
  }
  return out
}

describe('feature catalog ⇄ FEATURES.md sync', () => {
  const sheet = parseCheatSheet()

  it('should have every cheat-sheet row in the catalog (same category)', () => {
    const catalogKeys = new Set(FEATURE_CATALOG.map(e => `${e.category}|${e.name}`))
    const missing = sheet.filter(r => !catalogKeys.has(`${r.category}|${r.name}`))
    assert.deepEqual(missing, [], `rows in FEATURES.md missing from the catalog`)
  })

  it('should have every catalog entry in the cheat sheet (same category)', () => {
    const sheetKeys = new Set(sheet.map(r => `${r.category}|${r.name}`))
    const missing = FEATURE_CATALOG.filter(e => !sheetKeys.has(`${e.category}|${e.name}`))
    assert.deepEqual(
      missing.map(e => `${e.category}|${e.name}`),
      [],
      'catalog entries missing from FEATURES.md'
    )
  })

  it('should reference only commands that exist in the manifest (or view focus commands)', () => {
    const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8')) as {
      contributes: { commands: Array<{ command: string }>; views: Record<string, Array<{ id: string }>> }
    }
    const declared = new Set(manifest.contributes.commands.map(c => c.command))
    for (const views of Object.values(manifest.contributes.views)) {
      for (const view of views) {
        declared.add(`${view.id}.focus`) // auto-generated by VS Code per view
      }
    }
    const unknown = FEATURE_CATALOG.filter(e => e.command && !declared.has(e.command))
    assert.deepEqual(
      unknown.map(e => e.command),
      [],
      'catalog commands not declared in package.json'
    )
  })

  it('should have non-empty names, categories, and descriptions', () => {
    for (const entry of FEATURE_CATALOG) {
      assert.ok(entry.name.length > 0)
      assert.ok(entry.category.length > 0)
      assert.ok(entry.description.length > 10, `description too short for ${entry.name}`)
    }
  })

  it('should keep entries grouped by category (separators render once per group)', () => {
    const seen = new Set<string>()
    let last = ''
    for (const entry of FEATURE_CATALOG) {
      if (entry.category !== last) {
        assert.ok(!seen.has(entry.category), `category ${entry.category} appears in two separate blocks`)
        seen.add(entry.category)
        last = entry.category
      }
    }
  })
})
